### ISSUE TITLE
选择web模式之后不扫描二维码，直接关掉窗口之后会报错并且接下来无法打开软件了

### ISSUE THREAD

**Issue by a1047707793a** [GC-Ruth/Genshin-Impact-Point_Switch#2]
![image](https://user-images.githubusercontent.com/123014254/223883239-210d9774-aac1-46b0-863d-d82217ba1c6b.png)
把程序关掉之后再打开也会这样

**Comment by a1047707793a** [comment]
这是文字形式，方便作者复制调试：

Traceback (most recent call last):
  File "point_switch1.6.2.py", line 475, in <module>
  File "point_switch1.6.2.py", line 48, in __init__
  File "point_switch1.6.2.py", line 335, in Config
  File "configparser.py", line 963, in __getitem__
KeyError: 'General'

**Comment by GC-Ruth** [comment]
这种情况直接删config文件应该能解决

**Comment by a1047707793a** [comment]
> 
好的 确实直接删掉就解决了
